### ISSUE TITLE
write! macro causes panics with crossterm::Screen

### ISSUE THREAD

**Issue by hawkw** [mgattozzi/ysh#12]
using the `write!` macro with `crossterm`'s `Screen` type causes the shell to panic with the message "failed to write whole buffer". 

This is a pain in the ass, since the alternatives are either use `format!("...", ...).to_bytes()` which @mgatozzi did here:
https://github.com/mgattozzi/ysh/blob/1a255f2ff09bb9cefe98ea9e8b7308f8f7b13341/src/term.rs#L43

or to `screen.write(...)` each part of a format string that implements `fmt::Display` individually, like I did here:
https://github.com/mgattozzi/ysh/blob/1a255f2ff09bb9cefe98ea9e8b7308f8f7b13341/src/term.rs#L79-L85

The first approach sucks because it allocates, and the second approach sucks because...it looks like that. It would be nice if we could just use the nice macro from the stdlib which AFAICT _should_ work.

**Comment by mgattozzi** [comment]
We could also create a `write` macro that expands out to your thing and just does all this. Hacky but better than either of these

**Comment by hawkw** [comment]
hot take: what if we just fixed, the bug,

**Comment by mgattozzi** [comment]
^ Let's fork it

**Comment by hawkw** [comment]
LOL CROSSTERM SWALLOWS BACKTRACES APPARENTLY I HAVE NO IDEA HOW TO FIX THIS

**Comment by hawkw** [comment]
lol i think i [found the bug](https://github.com/TimonPost/crossterm/blob/master/src/modules/output/ansi_output.rs#L17).

excuse me crossterm, wtf r u doin
<img width="345" alt="crossterm-wtf" src="https://user-images.githubusercontent.com/2796466/45579868-1edcba80-b840-11e8-8dc7-b2e5a72819ef.png">

**Comment by hawkw** [comment]
I've opened TimonPost/crossterm#31, after which we should be able to go back to depending on upstream.

**Comment by hawkw** [comment]
My PR has been upstreamed, so we can go back to depending on TimonPost/crossterm@master (not on crates.io yet).

**Comment by TimonPost** [comment]
I published version 4.2 with the changes as described above.

**Comment by mgattozzi** [comment]
Ah awesome thanks so much @TimonPost :D
