### ISSUE TITLE
Do we want to move this out of main?

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/ysh#19]
https://github.com/mgattozzi/ysh/blob/master/src/main.rs#L42-L116

Personally I lean towards yes and have main just start the program and that's it

**Comment by hawkw** [comment]
yeah, I think it should be moved, I just didn't want to deal with moving the imports at the time

**Comment by myrrlyn** [comment]
Yes. I will submit a PR that *just* empties main and moves everything to the library.

**Comment by hawkw** [comment]
we'll probably want `main` to handle like "are we running in interactive mode or executing a script" eventually?

**Comment by myrrlyn** [comment]
Right. Main should figure out if it's running in a terminal or not, and invoke the correct parts of the library to spin up a runloop or just evaluate some input.
