### ISSUE TITLE
No `exit` builtin

### ISSUE THREAD

**Issue by croyzor** [mgattozzi/ysh#32]
In other shells, there is a convention that the shell can be closed by typing `exit` or `^D` (the latter may not be cross platform). It seems that there's no way to exit `ysh` other than `SIGINT` (on linux)

**Comment by mgattozzi** [comment]
Hey @croyzor you're right and in fact it's not to hard to extend!

- We have the builtins [here](https://github.com/mgattozzi/ysh/blob/master/src/ast/builtin.rs). One would be needed to be added to the enum as `Exit`.

- [This line](https://github.com/mgattozzi/ysh/blob/master/src/st.rs#L68) would need to have a match for this new `Exit` one and that just needs to call `break` in the loop to stop the program.

- The [last bit](https://github.com/mgattozzi/ysh/blob/master/src/ast/builtin.rs#L26) is just adding "exit" to the match here and returning a `Ok(Builtin::Exit)`

A great first PR to get to know the repo and close your own issue at the same time! :D

**Comment by croyzor** [comment]
Thanks for the pointers! I've opened a pull request now :smile:

**Comment by mgattozzi** [comment]
Closed in #33! Thanks again!

**Comment by hawkw** [comment]
Very cool, thanks @croyzor! I think we'll also want to extend this to allow the user to pass an exit code (such as when scripts need to exit with an error code), but we can open an additional issue for that.
